version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
  redis-data:
services:
  app:
    build: ./infra/docker/php
    env_file: ./env.mariadb.local.env
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  web:
    build: ./infra/docker/nginx
    ports:
      - 80:80
      - 443:443
      - 5173:5173
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend

  db:
    build: ./infra/docker/mysql
    env_file: ./env.mariadb.local.env
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
  
  redis:
    image: redis:6.2.7
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - redis-data:/data